stubrunner:
  ids: com.thoughtworks:contract:+:stubs:8090
  repositoryRoot: http://localhost:8081/nexus/content/repositories/snapshots/
  stubs-mode: local
zuul:
  routes:
    product:
      path: /products/**
      url: http://localhost:8090/products
server:
  port: 8998
